# Generated by Django 5.0.6 on 2024-06-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_record_delete_item_delete_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
