# Generated by Django 5.0.6 on 2024-06-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_record_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
