# Generated by Django 5.0.6 on 2024-06-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_record_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
