# Generated by Django 5.0.6 on 2024-06-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_record_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
